In [30]:
import pandas as pd

In [32]:
data= pd.read_csv(r"C:\Users\andre\OneDrive\Documenti\Heuristics\MT_SA_Jigs\Data\Berwick_pred.csv")
data.head()

,Unnamed: 0,DocRef,RevNo,PNUmber,AssemblyRef,Stud,Len,Coil,TotOps,LIP_CUT_count,SWAGE_count,DIMPLE_count,NOTCH_count,WEB_count,SERVICE_HOLE_count,BOLT_count,END_TRUSS_count,Work Time
0,0,10300-MRT-Z1-00-DR-S-1002-01,C01,10300,Z1-00-1002-01,8,17884.80,100,63,15,15,30,3,0,0,0,0,214.42
1,1,10300-MRT-Z1-00-DR-S-1002-02,C01,10300,Z1-00-1002-02,14,23396.85,100,114,26,26,52,10,0,0,0,0,291.12
2,2,10300-MRT-Z1-00-DR-S-1003-01,C01,10300,Z1-00-1003-01,17,41170.61,100,183,41,41,82,19,0,0,0,0,508.71
3,3,10300-MRT-Z1-00-DR-S-1004-01,C02,10300,Z1-00-1004-01,15,17626.18,100,129,29,29,58,13,0,0,0,0,284.25
4,4,10300-MRT-Z1-00-DR-S-1004-02,C01,10300,Z1-00-1004-02,7,6557.92,100,40,10,10,20,0,0,0,0,0,112.76

In [33]:
deadline_map = {
    'Z1-01': '16-May-25',
    'Z1-00': '12-May-25',
    'Z2-01': '19-May-25',
    'Z2-00': '19-May-25',
    'Z4-01': '19-May-25',
    'Z4-00': '18-Jun-25',
    'Z3-01': '10-Jun-25',  
    'Z3-00': '02-Jul-25'  
}



# Extract the prefix (first two parts)
data['prefix'] = data['AssemblyRef'].str.extract(r'^(Z\d-\d{2})')

# Map the deadline
data['deadline'] = data['prefix'].map(deadline_map).fillna('1-Jun-25')

# Drop prefix column if not needed
data = data.drop(columns='prefix')

In [37]:
selected_df = data[['AssemblyRef', 'Len', 'Coil', 'Work Time', 'DIMPLE_count', 'deadline']].copy()
selected_df = selected_df.rename(columns={'Work Time': 'Howick Work Time'})
selected_df.head()

     AssemblyRef       Len  Coil  Howick Work Time  DIMPLE_count   deadline
0  Z1-00-1002-01  17884.80   100            214.42            30  12-May-25
1  Z1-00-1002-02  23396.85   100            291.12            52  12-May-25
2  Z1-00-1003-01  41170.61   100            508.71            82  12-May-25
3  Z1-00-1004-01  17626.18   100            284.25            58  12-May-25
4  Z1-00-1004-02   6557.92   100            112.76            20  12-May-25

In [38]:
selected_df.to_csv("Berwick_full_deadlines.csv")
# This output can be used for the howick and the jigs